import{a as E,S as P,i as c}from"./assets/vendor-hCbx__bN.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function f(o,t){return(await E.get("https://pixabay.com/api/",{params:{key:"56361798-f8b70e825b8ee5840492d6dfc",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:n,tags:e,likes:r,views:a,comments:w,downloads:S})=>`
          <li class="gallery-item">
            <a class="gallery-link" href="${n}">
              <img class="gallery-image" src="${i}" alt="${e}" />
            </a>
            <div class="info">
              <div class="info-item"><b>Likes</b><span>${r}</span></div>
              <div class="info-item"><b>Views</b><span>${a}</span></div>
              <div class="info-item"><b>Comments</b><span>${w}</span></div>
              <div class="info-item"><b>Downloads</b><span>${S}</span></div>
            </div>
          </li>
        `).join("");g.insertAdjacentHTML("beforeend",t),q.refresh()}function B(){g.innerHTML=""}function L(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function v(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const m=document.querySelector(".form"),M=document.querySelector(".load-more");let l="",s=1,u=0;m.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),s=1,l===""){c.warning({title:"Caution",message:"Please enter a search term!",position:"topRight"});return}B(),d(),L();try{const t=await f(l,s);if(t.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),u=Math.ceil(t.totalHits/15),s<u&&v()}catch{c.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{b(),m.reset()}});M.addEventListener("click",async()=>{s+=1,d(),L();try{const o=await f(l,s);y(o.hits);const t=document.querySelector(".gallery-item");if(t){const i=t.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}s>=u?(d(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch{c.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
